import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import './globals.css';

const geistSans = Roboto({
  subsets: ["vietnamese"],
});

export const metadata: Metadata = {
  title: "Boarding House",
  description: "Generated by tranluuquoctuan1906",
  icons: '/icons8-house-16.png',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className}`}
      >
        {children}
      </body>
    </html>
  );
}
